name: Run vulnerability scan
description: A custom action that will run vulnerability scans

inputs:
  src-dir:
    description: The directory of the source code
    required: true

runs:
  using: 'composite'
  steps:
    - id: trivy-db
      name: Check trivy db sha
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        endpoint='/orgs/aquasecurity/packages/container/trivy-db/versions'
        headers='Accept: application/vnd.github+json'
        jqFilter='.[] | select(.metadata.container.tags[] | contains("latest")) | .name | sub("sha256:";"")'
        sha=$(gh api -H "${headers}" "${endpoint}" | jq --raw-output "${jqFilter}")
        echo "Trivy DB sha256:${sha}"
        echo "sha=${sha}" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: .trivy
        key: ${{ runner.os }}-trivy-db-${{ steps.trivy-db.outputs.sha }}
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@0.24.0
      id: trivy
      continue-on-error: true
      with:
        scan-type: 'rootfs'
        scan-ref: ${{ inputs.src-dir }}
        trivy-config: trivy.yaml
    - name: Publish Trivy Output To Summary
      shell: bash
      if: ${{ steps.trivy.outcome == 'failure' }}
      run: |
        {
        echo "### Security Scan for ${{ inputs.pretty-name }}"
        echo "<details><summary>Click to expand</summary>"
        echo ""
        echo '```'
        cat trivy.txt
        echo '```'
        echo "</details>"
        } >> $GITHUB_STEP_SUMMARY
    - name: Fix .trivy permissions
      shell: bash
      run: sudo chown -R $(stat . -c %u:%g) .trivy
    - name: Fail on Vulnerabilities
      shell: bash
      if: ${{ steps.trivy.outcome == 'failure' }}
      run: |
        exit 1
