name: B2B Web SDK - Test & Deploy Node-API
on: workflow_dispatch
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun i
      - name: Checking for type errors
        run: bun run build
      - name: Checking for linting errors
        run: yarn lint
      - name: Yarn test
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: cd packages/node-api && yarn publish:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
