name: B2B Web SDK - Build and Test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'Test run'
  pull_request:
    branches: [main]
    paths:
      - '.github/**'
      - 'packages/**'
      - 'examples/**'
      - 'packages.json'
      - 'yarn.lock'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun i
      - name: Checking for type errors
        run: bun run build
      - name: Checking for linting errors
        run: yarn lint
      - name: Yarn test
        run: yarn test:cov
      - name: Yarn build
        run: yarn build
